// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Admin_Tools = "Admin Tools",
  Blue = "Blue",
  Blue2 = "Blue2",
  Blue_Spot = "Blue_Spot",
  Cinematic_Camera_Pivot = "Cinematic_Camera_Pivot",
  Firework_01 = "Firework_01",
  Firework_10 = "Firework_10",
  Firework_11 = "Firework_11",
  Firework_2 = "Firework_2",
  Firework_3 = "Firework_3",
  Firework_4 = "Firework_4",
  Firework_5 = "Firework_5",
  Firework_6 = "Firework_6",
  Firework_7 = "Firework_7",
  Firework_8 = "Firework_8",
  Firework_9 = "Firework_9",
  Fireworks = "Fireworks",
  Goal_Save_Collider = "Goal_Save_Collider",
  Goalkeeper = "Goalkeeper",
  Kicker = "Kicker",
  NPC_Blue_1 = "NPC_Blue_1",
  NPC_Blue_2 = "NPC_Blue_2",
  NPC_Blue_3 = "NPC_Blue_3",
  NPC_Blue_4 = "NPC_Blue_4",
  NPC_Blue_5 = "NPC_Blue_5",
  NPC_Red_1 = "NPC_Red_1",
  NPC_Red_2 = "NPC_Red_2",
  NPC_Red_3 = "NPC_Red_3",
  NPC_Red_4 = "NPC_Red_4",
  NPC_Red_5 = "NPC_Red_5",
  NPCs = "NPCs",
  Plaza = "Plaza",
  Red = "Red",
  Red_2 = "Red_2",
  Red_Spot = "Red_Spot",
  Sit_Spot = "Sit Spot",
  Sit_Spot_2 = "Sit Spot_2",
  Sit_Spot_3 = "Sit Spot_3",
  Sit_Spot_4 = "Sit Spot_4",
  Sit_Spot_5 = "Sit Spot_5",
  Sit_Spot_6 = "Sit Spot_6",
  Sit_Spot_7 = "Sit Spot_7",
  Sit_Spot_8 = "Sit Spot_8",
  Sit_Spots = "Sit_Spots",
  Spot_Lights = "Spot Lights",
  Spot_Rotation_1 = "Spot Rotation_1",
  Spot_Rotation_2 = "Spot Rotation_2",
  Spot_Rotation_3 = "Spot Rotation_3",
  Spot_Rotation_4 = "Spot Rotation_4",
  Spotlight = "Spotlight",
  Spotlight_2 = "Spotlight_2",
  Spotlight_3 = "Spotlight_3",
  Spotlight_4 = "Spotlight_4",
  Video_Screen = "Video Screen",
  arrow_glb = "arrow.glb",
  ball_glb = "ball.glb",
  door_glb = "door.glb",
  event_card_bottom_tall_glb = "event_card_bottom_tall.glb",
  event_card_thumbnail_glb = "event_card_thumbnail.glb",
  futbol_arena_glb = "futbol_arena.glb",
  plaza_glb = "plaza.glb",
  portalFrame_glb = "portalFrame.glb",
  portalFrameArrows_glb = "portalFrameArrows.glb",
  portalLayer2_glb = "portalLayer2.glb",
  stadium_flags_glb = "stadium_flags.glb",
} 
